##
## Build
##
FROM golang:1.18 AS build

WORKDIR /

COPY . /

RUN go build -o ./clientLoader/cmd/main ./clientLoader/cmd/main.go

##
## Deploy
##
FROM alpine:3.16

WORKDIR /

COPY --from=build clientLoader/cmd/main .

ENTRYPOINT ["/app/main"]
