##
## Build
##
FROM golang:1.18 AS build

WORKDIR /

COPY . /

RUN go build -o ./serverDomain/cmd/main ./serverDomain/cmd/main.go

##
## Deploy
##
FROM alpine:3.16

WORKDIR /

COPY --from=build serverDomain/cmd/main .

ENTRYPOINT ["/app/main"]
